---
- name: Install default mariadb server
  hosts: dbservers
  become: true

  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present

    - name: Install key
      apt_key:
        url: "https://mariadb.org/mariadb_release_signing_key.asc"
        state: present

    - name: Install MariaDB repository 10.3
      apt_repository: repo='deb [arch=amd64,arm64,ppc64el] https://mirror.rackspace.com/mariadb/repo/10.3/ubuntu focal main'

    - name: Update packages
      apt:
        update_cache: true
        upgrade: true

    - name: Install mariadb-server
      apt:
        name: mariadb-server
        state: present

    - name: Install MariaDB Client 10.3
      apt:
        name: mariadb-client
        state: present

    - name: Enabled on boot
      service:
        name: mysql
        state: started

    - name: Make sure pymysql is present
      apt:
        name: python3-mysqldb
        state: present

    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"
        host: localhost

    - name: remove remote root
      mysql_user:
        check_implicit_admin: true
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        host: "{{ ansible_fqdn }}"
        state: absent

    - name: Restart MariaDB 10.3
      service:
        name: mysql
        state: restarted
